# global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'
    scrape_interval: 10s 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'cadvisor'

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
#    scrape_interval: 5s
#
#    dns_sd_configs:
#    - names:
#      - 'tasks.node-exporter'
#      type: 'A'
#      port: 9100    
    static_configs:
      - targets: ['node-exporter:9100']
